apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
spec:
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: landing-page
        image: dzikrihuda/landingpage:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: landing-svc
spec:
  selector:
    app: landing
  ports:
  - port: 90
    targetPort: 80
  type: LoadBalancer