apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed
spec:
  selector:
    matchLabels:
      app: sosmed
  template:
    metadata:
      labels:
        app: sosmed
    spec:
      containers:
      - name: sosmed
        image: dzikrihuda/sosmed:v1.0
        env:
        - name: host
          value: db-sosmed.cmujp7o5mm0w.ap-southeast-2.rds.amazonaws.com
        - name: user
          value: admin
        - name: pass
          value: ifsaktii
        - name: name
          value: sosmed
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sosmed-svc
spec:
  selector:
    app: sosmed
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
